version: '3.7'

services:
    app:
        build: ./
        command: streamlit run main.py --server.port 8501
        volumes:
            - ./app:/usr/src/app
        ports:
            - 8501:8501
        image: yourstreamlitapp:latest
        networks:
          - app
        container_name: streamlit_app

networks:
  app:
    driver: bridge